// Package cligen generates a self-contained bash CLI wrapper from an ACL schema.
//
// The generated script exposes each AGENT as a kebab-case sub-command and
// delegates to `acl run --agent <Name>`.  It works standalone — no server
// required — and can be called by any LLM agent via shell.
//
// Example output (for splitwise.acl):
//
//	./splitwise create-group --var name="Spain Trip" --var members="alice,bob"
//	./splitwise add-expense   --var group_id=abc123 --var amount=85.50
//	./splitwise --help
package cligen

import (
	"fmt"
	"strings"
	"text/template"
	"bytes"

	"github.com/ranausmanai/acl/internal/schema"
)

const scriptTmpl = `#!/usr/bin/env bash
# ────────────────────────────────────────────────────────────────────────────
#  {{.Name}} — auto-generated CLI
#  Intent : {{.Intent}}
#  Source : {{.ACLFile}}
#  Generated by: acl cli
# ────────────────────────────────────────────────────────────────────────────
set -euo pipefail

_ACL_FILE="${ACL_FILE:-{{.ACLFile}}}"
_ACL_BIN="${ACL_BIN:-acl}"

# ── help ─────────────────────────────────────────────────────────────────────
_usage() {
  cat << 'HELPTEXT'
{{.Name}} — {{.Intent}}

COMMANDS
{{- range .Agents}}
  {{padRight .CLI 22}} {{.InputSummary}}{{if .Schedule}}  [scheduled: {{.Schedule}}]{{end}}
{{- end}}

USAGE
  {{.Name}} <command> [--var key=value ...]
  {{.Name}} <command> --help

EXAMPLES
{{- range .Agents}}{{if .HasInputs}}
  {{$.Name}} {{.CLI}}{{range .Inputs}} --var {{.Name}}=<{{.Name}}>{{end}}
{{- end}}{{end}}

FLAGS
  --var  key=value    Set an input variable (repeatable)
  --no-cache          Disable step result cache
  --receipt <path>    Write receipt JSON to this path

ENVIRONMENT
  ACL_FILE   Path to the .acl file  (default: {{.ACLFile}})
  ACL_BIN    Path to the acl binary (default: acl)
HELPTEXT
}

# ── dispatch ──────────────────────────────────────────────────────────────────
case "${1:-}" in
{{- range .Agents}}
  {{.CLI}})
    shift
    exec "$_ACL_BIN" run "$_ACL_FILE" --agent {{.Name}} "$@"
    ;;
{{- end}}
  help|--help|-h|"")
    _usage
    ;;
  *)
    echo "error: unknown command '${1}'" >&2
    echo ""                               >&2
    _usage                                >&2
    exit 1
    ;;
esac
`

// AgentView is the template view of one agent.
type AgentView struct {
	Name     string
	CLI      string
	Inputs   []schema.InputParam
	Schedule string
}

func (a AgentView) HasInputs() bool { return len(a.Inputs) > 0 }

func (a AgentView) InputSummary() string {
	if len(a.Inputs) == 0 {
		return "(no inputs)"
	}
	parts := make([]string, len(a.Inputs))
	for i, inp := range a.Inputs {
		parts[i] = inp.Name
	}
	return "[in: " + strings.Join(parts, ", ") + "]"
}

// TemplateData is passed to the bash script template.
type TemplateData struct {
	Name    string
	Intent  string
	ACLFile string
	Agents  []AgentView
}

// Generate produces a bash wrapper script from the given schema.
//
//   - name    is the CLI binary name (e.g. "splitwise")
//   - aclFile is the path to the .acl file the script should call
func Generate(svc *schema.ServiceSchema, name, aclFile string) (string, error) {
	if name == "" {
		name = "service"
	}

	views := make([]AgentView, len(svc.Agents))
	for i, a := range svc.Agents {
		views[i] = AgentView{
			Name:     a.Name,
			CLI:      a.CLI,
			Inputs:   a.Inputs,
			Schedule: a.Schedule,
		}
	}

	data := TemplateData{
		Name:    name,
		Intent:  svc.Intent,
		ACLFile: aclFile,
		Agents:  views,
	}

	funcMap := template.FuncMap{
		"padRight": func(s string, n int) string {
			if len(s) >= n {
				return s
			}
			return s + strings.Repeat(" ", n-len(s))
		},
	}

	tmpl, err := template.New("cli").Funcs(funcMap).Parse(scriptTmpl)
	if err != nil {
		return "", fmt.Errorf("cligen: template parse: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("cligen: template execute: %w", err)
	}
	return buf.String(), nil
}
